const data = {
  topSellersProducts: [
    {
      _id: "product001",
      image: "/images/image_001.png",
      name: "Product 1",
      description: "Description 1",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product002",
      image: "/images/image_002.png",
      name: "Product 2",
      description: "Description 2",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product003",
      image: "/images/image_003.png",
      name: "Product 3",
      description: "Description 3",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product004",
      image: "/images/image_004.png",
      name: "Product 4",
      description: "Description 4",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product005",
      image: "/images/image_005.png",
      name: "Product 5",
      description: "Description 5",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product006",
      image: "/images/image_006.png",
      name: "Product 6",
      description: "Description 6",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
  ],
  topOffersProducts: [
    {
      _id: "product007",
      image: "/images/image_007.png",
      name: "Product 7",
      description: "Description 7",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product008",
      image: "/images/image_008.png",
      name: "Product 8",
      description: "Description 8",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product009",
      image: "/images/image_009.png",
      name: "Product 9",
      description: "Description 9",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product010",
      image: "/images/image_010.png",
      name: "Product 10",
      description: "Description 10",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product011",
      image: "/images/image_011.png",
      name: "Product 11",
      description: "Description 11",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product012",
      image: "/images/image_012.png",
      name: "Product 12",
      description: "Description 12",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
  ],
  topDealsProducts: [
    {
      _id: "product013",
      image: "/images/image_013.png",
      name: "Product 13",
      description: "Description 13",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product014",
      image: "/images/image_014.png",
      name: "Product 14",
      description: "Description 14",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product015",
      image: "/images/image_015.png",
      name: "Product 15",
      description: "Description 15",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product016",
      image: "/images/image_016.png",
      name: "Product 16",
      description: "Description 16",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product017",
      image: "/images/image_017.png",
      name: "Product 17",
      description: "Description 17",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
    {
      _id: "product018",
      image: "/images/image_018.png",
      name: "Product 18",
      description: "Description 18",
      retailPrice: 1200,
      wholeSalePrice: 800,
      discount: 30,
    },
  ],
};

export default data;
